# Generated by Django 5.2.5 on 2025-08-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaitem",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="covers/default_cover.jpg",
                null=True,
                upload_to="covers/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.jpg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
