# Generated by Django 5.2.5 on 2025-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_mediaitem_cover_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="images/covers/default_cover.jpg",
                null=True,
                upload_to="images/covers/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/avatars/default_avatar.jpg",
                null=True,
                upload_to="images/avatars/",
            ),
        ),
    ]
