# Generated by Django 5.2.5 on 2025-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_mediaitem_cover_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="images/covers/"),
        ),
    ]
