# Generated by Django 5.2.5 on 2025-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_mediaitem_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In progress"),
                    ("finished", "Finished"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
