# Generated by Django 5.2.5 on 2025-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_usermedia_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(default="default_text", max_length=255),
            preserve_default=False,
        ),
    ]
