# Generated by Django 5.2.5 on 2025-09-14 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_alter_mediaitem_cover_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="cover",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
