# Generated by Django 5.2.5 on 2025-09-14 19:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_alter_mediaitem_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
